"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDownRight, ArrowUpRight, BarChart3, ChartNoAxesCombined, Target, TrendingUp } from "lucide-react";
import { AppChrome } from "../components/AppChrome";
import { useWeb3 } from "../context/Web3Context";
import { useAppSettings } from "../context/AppSettingsContext";
import { useEntries, type Entry as LedgerEntry } from "../../lib/hooks/useEntries";

const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const chartColors = ["#8edcff", "#ff9a9a", "#76f0c1", "#ffd98a", "#b7a9ff", "#f4a6d7"];
function format(value: number, hidden = false) { return hidden ? "••••••" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value || 0); }
const formatTooltip = (value: unknown) => [format(Number(value)), ""] as [string, string];
const formatOutgoingTooltip = (value: unknown) => [format(Number(value)), "Outgoing"] as [string, string];
function entriesToRows(entries: LedgerEntry[], crypto: boolean) { return entries.map((entry) => { const income = crypto ? Number(entry.currentValue || entry.investmentAmount || 0) : Number(entry.earned || 0); const expense = crypto ? 0 : Number(entry.given || 0); return { ...entry, income, expense, category: entry.givenTo || entry.project || "Other" }; }); }

export default function PerformancePage() {
  const { isWeb3 } = useWeb3();
  const { hideBalances } = useAppSettings();
  const { web2Entries, web3Entries } = useEntries(isWeb3);
  const [chartType, setChartType] = useState<"area" | "bar">("area");
  const entries = useMemo(() => entriesToRows(isWeb3 ? web3Entries : web2Entries, isWeb3), [web2Entries, web3Entries, isWeb3]);
  const monthly = useMemo(() => monthNames.map((month, index) => { const rows = entries.filter((entry) => new Date(entry.date).getMonth() === index); const income = rows.reduce((sum, entry) => sum + entry.income, 0); const expense = rows.reduce((sum, entry) => sum + entry.expense, 0); return { month, income, expense, saved: Math.max(0, income - expense), ratio: income ? Math.round(((income - expense) / income) * 100) : 0 }; }), [entries]);
  const activeMonths = monthly.filter((month) => month.income || month.expense);
  const totalIncome = entries.reduce((sum, entry) => sum + entry.income, 0);
  const totalExpense = entries.reduce((sum, entry) => sum + entry.expense, 0);
  const totalSaved = Math.max(0, totalIncome - totalExpense);
  const avgRatio = activeMonths.length ? Math.round(activeMonths.reduce((sum, month) => sum + month.ratio, 0) / activeMonths.length) : 0;
  const categoryData = useMemo(() => { const map = new Map<string, number>(); entries.forEach((entry) => map.set(entry.category, (map.get(entry.category) || 0) + entry.expense)); return [...map.entries()].sort((a, b) => b[1] - a[1]).slice(0, 6).map(([name, value], index) => ({ name, value, color: chartColors[index % chartColors.length] })); }, [entries]);
  const tooltip = { contentStyle: { background: "var(--panel-strong)", border: "1px solid var(--line-strong)", borderRadius: 12, color: "var(--text)", fontSize: 11 }, labelStyle: { color: "var(--text)" } };

  return <AppChrome title="Analytics"><div className="page-heading"><div><p className="eyebrow">Signal room / performance</p><h1>See the pattern.</h1><p>Turn transactions into decisions with a compact read on income, outgoing flow, savings, and category weight.</p></div><div className="page-heading__actions"><div className="mode-switch"><button className={chartType === "area" ? "is-active" : ""} onClick={() => setChartType("area")}>Area</button><button className={chartType === "bar" ? "is-active" : ""} onClick={() => setChartType("bar")}>Bars</button></div></div></div>
    <div className="page-grid"><div className="panel"><div className="panel__content"><span className="glyph-label">Total inflow</span><p className="balance-hero__value" style={{ fontSize: 33, marginTop: 20 }}>{format(totalIncome, hideBalances)}</p><p className="panel-subtitle"><ArrowDownRight size={13} style={{ verticalAlign: "-2px", color: "var(--mint)" }} /> income / asset movement</p></div></div><div className="panel"><div className="panel__content"><span className="glyph-label">Total outgoing</span><p className="balance-hero__value" style={{ fontSize: 33, marginTop: 20 }}>{format(totalExpense, hideBalances)}</p><p className="panel-subtitle"><ArrowUpRight size={13} style={{ verticalAlign: "-2px", color: "var(--coral)" }} /> spending / allocation</p></div></div><div className="panel"><div className="panel__content"><span className="glyph-label">Savings ratio</span><p className="balance-hero__value" style={{ fontSize: 33, marginTop: 20 }}>{hideBalances ? "••%" : `${avgRatio}%`}</p><p className="panel-subtitle"><TrendingUp size={13} style={{ verticalAlign: "-2px", color: "var(--sky)" }} /> {totalSaved ? `${format(totalSaved, hideBalances)} net retained` : "Add data to unlock insight"}</p></div></div></div>
    <section className="panel chart-panel"><div className="panel__content"><div className="panel-title-row"><div><span className="glyph-label">Monthly overview / 12 points</span><h2 className="panel-title" style={{ marginTop: 10 }}>Inflow vs outgoing</h2><p className="panel-subtitle">A normalized view of your current ledger history.</p></div><ChartNoAxesCombined size={18} color="var(--sky)" /></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%">{chartType === "area" ? <AreaChart data={monthly} margin={{ top: 12, right: 4, left: -25, bottom: 0 }}><defs><linearGradient id="perfIncome" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8edcff" stopOpacity={0.3} /><stop offset="100%" stopColor="#8edcff" stopOpacity={0} /></linearGradient><linearGradient id="perfExpense" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ff9a9a" stopOpacity={0.22} /><stop offset="100%" stopColor="#ff9a9a" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="rgba(183,224,255,0.1)" strokeDasharray="3 7" vertical={false} /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "var(--text-faint)", fontSize: 10 }} dy={10} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "var(--text-faint)", fontSize: 10 }} tickFormatter={(value) => `$${Math.round(value / 1000)}k`} /><Tooltip {...tooltip} formatter={formatTooltip} /><Area type="monotone" dataKey="income" name="Income" stroke="#8edcff" strokeWidth={2.5} fill="url(#perfIncome)" /><Area type="monotone" dataKey="expense" name="Outgoing" stroke="#ff9a9a" strokeWidth={2} fill="url(#perfExpense)" /></AreaChart> : <BarChart data={monthly} margin={{ top: 12, right: 4, left: -25, bottom: 0 }}><CartesianGrid stroke="rgba(183,224,255,0.1)" strokeDasharray="3 7" vertical={false} /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "var(--text-faint)", fontSize: 10 }} dy={10} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "var(--text-faint)", fontSize: 10 }} tickFormatter={(value) => `$${Math.round(value / 1000)}k`} /><Tooltip {...tooltip} formatter={formatTooltip} /><Bar dataKey="income" name="Income" fill="#8edcff" radius={[5, 5, 0, 0]} /><Bar dataKey="expense" name="Outgoing" fill="#ff9a9a" radius={[5, 5, 0, 0]} /></BarChart>}</ResponsiveContainer></div><div className="chart-legend"><span className="legend-item"><i />Income / asset inflow</span><span className="legend-item"><i className="coral" />Outgoing / spend</span></div></div></section>
    <div className="grid-two"><section className="panel"><div className="panel__content"><div className="panel-title-row"><div><span className="glyph-label">Category weight</span><h2 className="panel-title" style={{ marginTop: 10 }}>Where it goes</h2></div><BarChart3 size={18} color="var(--gold)" /></div>{categoryData.length ? <div style={{ display: "flex", alignItems: "center", gap: 18, marginTop: 20 }}><div style={{ width: 170, height: 170, flex: "0 0 auto" }}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categoryData} dataKey="value" innerRadius={48} outerRadius={72} paddingAngle={3} stroke="none">{categoryData.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip {...tooltip} formatter={formatOutgoingTooltip} /></PieChart></ResponsiveContainer></div><div style={{ display: "grid", gap: 11, minWidth: 0, flex: 1 }}>{categoryData.map((item) => <div key={item.name} style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 11 }}><span style={{ width: 7, height: 7, borderRadius: 2, background: item.color }} /><span style={{ flex: 1, overflow: "hidden", color: "var(--text-soft)", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{item.name}</span><strong style={{ color: "var(--text)", fontFamily: "var(--font-mono)", fontSize: 10 }}>{format(item.value, hideBalances)}</strong></div>)}</div></div> : <div className="empty-state" style={{ marginTop: 20 }}><div><BarChart3 size={21} /><p>No category weight yet</p><span>Outgoing transactions will appear here.</span></div></div>}</div></section><section className="panel"><div className="panel__content"><div className="panel-title-row"><div><span className="glyph-label">Retention</span><h2 className="panel-title" style={{ marginTop: 10 }}>Keep rate</h2></div><Target size={18} color="var(--mint)" /></div><div style={{ marginTop: 28, display: "grid", placeItems: "center" }}><div className="score-ring" style={{ width: 118, height: 118, fontSize: 24 }}>{hideBalances ? "••%" : `${avgRatio}%`}</div></div><p style={{ textAlign: "center", color: "var(--text-soft)", fontSize: 11, lineHeight: 1.6, margin: "22px 12px 0" }}>The percentage of recorded inflow that stayed in your balance after outgoing activity.</p></div></section></div>
    <section className="panel table-panel"><div className="panel__content"><div className="panel-title-row"><div><span className="glyph-label">Breakdown / monthly</span><h2 className="panel-title" style={{ marginTop: 10 }}>The ledger, summarized</h2></div></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Month</th><th>Income</th><th>Outgoing</th><th>Retained</th><th>Keep rate</th></tr></thead><tbody>{monthly.filter((month) => month.income || month.expense).map((month) => <tr key={month.month}><td><strong>{month.month}</strong></td><td style={{ color: "var(--mint)" }}>{format(month.income, hideBalances)}</td><td style={{ color: "var(--coral)" }}>{format(month.expense, hideBalances)}</td><td style={{ color: "var(--sky)" }}>{format(month.saved, hideBalances)}</td><td><span className="glyph-label" style={{ color: month.ratio >= 0 ? "var(--mint)" : "var(--coral)" }}>{hideBalances ? "••%" : `${month.ratio}%`}</span></td></tr>)}{!activeMonths.length && <tr><td colSpan={5}><div className="empty-state">Add transactions to generate a monthly breakdown.</div></td></tr>}</tbody></table></div></section>
  </AppChrome>;
}
